WebApplication1/Controllers/AlunoController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using WebApplication1.Models;

namespace WebApplication1.Controllers
{
    public class AlunoController : Controller
    {     
        private ApplicationDbContext _context;

        public AlunoController()
        {
            _context = new ApplicationDbContext();
        }

        protected override void Dispose(bool disposing)
        {
            _context.Dispose();
        }

        // GET: /Aluno/
        public ActionResult Index()
        {
            var alunos = _context.Alunos.ToList();
            return View(alunos);
        }

        public ActionResult Details(int id)
        {
            var aluno = _context.Alunos.SingleOrDefault(a => a.Id == id);

            if (aluno == null)
                return HttpNotFound();

            return View(aluno);
        }
	}
}

WebApplication1/Controllers/FaixaController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using WebApplication1.Models;

namespace WebApplication1.Controllers
{
    public class FaixaController : Controller
    {     
        private ApplicationDbContext _context;

        public FaixaController()
        {
            _context = new ApplicationDbContext();
        }

        protected override void Dispose(bool disposing)
        {
            _context.Dispose();
        }

        // GET: /Faixa/
        public ActionResult Index()
        {
            var faixas = _context.Faixas.ToList();
            return View(faixas);
        }

        public ActionResult Details(int id)
        {
            var faixa = _context.Faixas.SingleOrDefault(a => a.Id == id);

            if (faixa == null)
                return HttpNotFound();

            return View(faixa);
        }
	}
}

WebApplication1/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>@ViewBag.Title - Artes Marciais MVC</title>
    @Styles.Render("~/Content/css")
    @Scripts.Render("~/bundles/modernizr")

</head>
<body>
    @Html.Partial("_NavBarCentral");
    <div class="container body-content">
        @RenderBody()
        <hr />
        <footer>
            <p>&copy; @DateTime.Now.Year - Artes Marciais MVC</p>
        </footer>
    </div>

    @Scripts.Render("~/bundles/jquery")
    @Scripts.Render("~/bundles/bootstrap")
    @RenderSection("scripts", required: false)
</body>
</html>

WebApplication1/Views/Shared/_NavBarCentral.cshtml
<div class="navbar navbar-inverse navbar-fixed-top">
    <div class="container">
        <div class="navbar-header">
            <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
                <span class="icon-bar"></span>
                <span class="icon-bar"></span>
                <span class="icon-bar"></span>
            </button>
            @Html.ActionLink("Artes Marciais MVC", "Index", "Aluno", new { area = "" }, new { @class = "navbar-brand" })
        </div>
        <div class="navbar-collapse collapse">
            <ul class="nav navbar-nav">
                <li>@Html.ActionLink("Alunos", "Index", "Aluno")</li>
                <li>@Html.ActionLink("Tipos de Associação", "Index", "TipodeAssociao")</li>
                <li>@Html.ActionLink("Faixas", "Index", "Faixa")</li>
            </ul>
            @Html.Partial("_LoginPartial")
        </div>
    </div>
</div>